SUPER_CONFIG_PATH: ./motip/configs/r50_deformable_detr_motip_sportsmot.yaml

DATASETS: [SquashTrack]
DATASET_SPLITS: [train]

DETR_PRETRAIN: ./pretrains/r50_deformable_detr_coco_sportsmot.pth
RESUME_MODEL: ./pretrains/r50_deformable_detr_motip_sportsmot.pth
RESUME_OPTIMIZER: False
RESUME_SCHEDULER: False
RESUME_STATES: False

INFERENCE_DATASET:
INFERENCE_SPLIT:

LR: 1.0e-5
LR_WARMUP_EPOCHS: 1
EPOCHS: 8
SCHEDULER_MILESTONES: [5, 7]
SAVE_CHECKPOINT_PER_EPOCH: 1

NUM_WORKERS: 1
PREFETCH_FACTOR: 2

BATCH_SIZE: 1
ACCUMULATE_STEPS: 1
SAMPLE_LENGTHS: [60, ]
DETR_NUM_TRAIN_FRAMES: 4
DETR_NUM_CHECKPOINT_FRAMES: 5
USE_DECODER_CHECKPOINT: True
